name: DL
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - filelock==3.20.0
      - fsspec==2025.10.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.6
      - numpy==2.3.5
      - pillow==12.0.0
      - sympy==1.14.0
      - torch==2.9.1
      - torchaudio==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - wget==3.2
prefix: /opt/anaconda3/envs/DL
